name: Keep Supabase Alive

on:
  schedule:
    # S'exécute tous les 3 jours à minuit
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          curl -s -X GET "https://gupljpcqwfccjdrepdlc.supabase.co/rest/v1/site_stats?select=id&limit=1" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cGxqcGNxd2ZjY2pkcmVwZGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3MjkxNjUsImV4cCI6MjEwNDMwNTE2NX0.f9itEah0tNQID7EocmWrJOXfsAzRsYWljw24mpt8Td8" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cGxqcGNxd2ZjY2pkcmVwZGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3MjkxNjUsImV4cCI6MjEwNDMwNTE2NX0.f9itEah0tNQID7EocmWrJOXfsAzRsYWljw24mpt8Td8"